/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

int main(void)
{
    /* Loop forever */
	uint32_t *pClkCtrlReg   = (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg  = (uint32_t*)0x40020C14;



//	1. Enable the clock for GPIOD peripheral in the AHBENR
//	uint32_t temp = *pClkCtrlReg;	// read operation
//	temp = temp | 0x08;				// modify
//	*pClkCtrlReg = temp;			// write back

	// Shorter version of the above 3 lines
//	*pClkCtrlReg = *pClkCtrlReg | 0x08;

	// More shorter version
//	*pClkCtrlReg |= 0x08;

	// now using lest shift operator <<
	*pClkCtrlReg |= (1 << 3);



// 2. configure the mode of the IO pin as output
	// a. clear the 24th and 25th bit positions (CLEAR)
//	*pPortDModeReg &= 0xFCFFFFFF;

	// now using lest shift operator <<
	*pPortDModeReg &= ~(3 << 26);

	// b. make 24th bit position as 1 (SET)
//	*pPortDModeReg |= 0x01000000;

	// now using lest shift operator <<
	*pPortDModeReg |= (1 << 26);





// 3. SET 12th bit of the output data register to make I/O pin-12 as HIGH.
//	*pPortDOutReg |= 0x1000;

	// now using lest shift operator <<
	*pPortDOutReg |= (1 << 13);



	for(;;);
}
